version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - mongo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    ports:
      - '27017:27017'
    healthcheck:
      test: [ 'CMD', 'mongosh', '--eval', 'db.adminCommand("ping")' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  benchmark_mongo:
    build: './mongo_db'
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin_password
      - MONGO_AUTH_SOURCE=admin
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["sh", "-c", "python benchmark_mongo.py"]

networks:
  mongo-network: