services:
  payment-service:
    build: ./compose/billing/payment
    networks:
      - movies-network
    command: [ '/opt/app/commands/fastapi.sh', 'dev' ]
    healthcheck:
      test: [ 'CMD-SHELL', 'curl -s http://localhost:8000/payment/api/_health' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - SERVICE_URL=$SERVICE_URL
      - YOOMONEY_CLIENT_ID=$YOOMONEY_CLIENT_ID
      - YOOMONEY_REDIRECT_URI=$YOOMONEY_REDIRECT_URI
      - YOOMONEY_SECRET=$YOOMONEY_SECRET
      - YOOMONEY_RECEIVER_ACCOUNT=$YOOMONEY_RECEIVER_ACCOUNT
      - YOOMONEY_TOKEN_ACCOUNT=$YOOMONEY_TOKEN_ACCOUNT
      - RABBITMQ_USERNAME=$BILLING_RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD=$BILLING_RABBITMQ_PASSWORD
      - RABBITMQ_HOST=billing-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=payment-redis
      - REDIS_PORT=6379
    depends_on:
      billing-rabbitmq:
        condition: service_healthy
    ports:
      - '8000:8000'
    develop:
      watch:
        - action: sync
          path: ./compose/billing/payment/src
          target: /opt/app/src
        - action: rebuild
          path: ./compose/billing/payment/commands
        - action: rebuild
          path: ./compose/billing/payment/pyproject.toml
        - action: rebuild
          path: ./compose/billing/payment/poetry.lock

  payment-redis:
    image: 'bitnami/redis:7.4.2-debian-12-r0'
    networks:
      - movies-network
    volumes:
      - 'payment-redis-data:/bitnami/redis/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: [ '/opt/bitnami/scripts/redis/run.sh', '--maxmemory', '${AUTH_REDIS_MAXMEMORY:-200mb}' ]
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', '/bin/bash', '-c', '[[ $(redis-cli ping) == "PONG" ]]' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  billing-rabbitmq:
    image: 'bitnami/rabbitmq:4.0.7-debian-12-r1'
    networks:
      - movies-network
    volumes:
      - 'billing-rabbitmq-data:/bitnami/rabbitmq/mnesia'
    environment:
      - RABBITMQ_USERNAME=$BILLING_RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD=$BILLING_RABBITMQ_PASSWORD
      - RABBITMQ_LOGS=-
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    restart: unless-stopped
    ports:
      - '15672:15672'
    healthcheck:
      test: [ 'CMD-SHELL', 'rabbitmq-diagnostics -q ping' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s

  short-link-redis:
    image: 'bitnami/redis:7.4.2-debian-12-r0'
    networks:
      - movies-network
    volumes:
      - short_links_redis_data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: [ '/opt/bitnami/scripts/redis/run.sh', '--maxmemory', '200m' ]
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', '/bin/bash', '-c', '[[ $(redis-cli ping) == "PONG" ]]' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  short-link-service:
    build: ./compose/notifications/short_links
    networks:
      - movies-network
    depends_on:
      short-link-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=short-link-redis
      - REDIS_PORT=6379
      - PROJECT_HOST

networks:
  movies-network:

volumes:
  billing-rabbitmq-data:
  short_links_redis_data:
  payment-redis-data: