include:
  - compose.yaml

services:
  faker:
    build: 
      context: ./faker
    depends_on:
        postgresql:
          condition: service_healthy
    networks:
      - movies-network
    environment:
      - POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD


networks:
  movies-network:

volumes:
  redis-data:
  elasticsearch-data:
  etl-data:
  etl-logs:
  postgresql-data:
