name: online-theatre-tests

services:
  tests:
    build:
      context: ./tests
    depends_on:
      movies:
        condition: service_healthy
    networks:
      - movies-network
    environment:
      - MOVIES_URL=http://movies:8000

  movies:
    extends:
      file: compose.yaml
      service: movies

  redis:
    extends:
      file: compose.yaml
      service: redis

  elasticsearch:
    extends:
      file: compose.yaml
      service: elasticsearch

networks:
  movies-network:

volumes:
  redis-data:
  elasticsearch-data:
