services:
  tests:
    volumes:
      - ./tests/tests/functional/src:/opt/app/tests/functional/src

  redis:
    ports:
      - '6379:6379'

  elasticsearch:
    ports:
      - '9200:9200'

  postgresql:
    ports:
      - '5432:5432'
