[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = { version = "0.115.6", extras = ["standard"] }
redis = "^5.2.1"
pydantic = "2.10.3"
pydantic-settings = "2.6.1"