version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - websockets-network
    environment:
      - HOST=0.0.0.0
      - PORT=8000

networks:
  websockets-network: