version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shortening-network

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - shortening-network
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  redis_data:
networks:
  shortening-network: