[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"

fastapi = { version = "0.115.6", extras = ["standard"] }
uvicorn-worker = "0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
