services:
  vertica:
    image: 'jbfavre/vertica:latest'
    container_name: 'vertica'
    ports:
      - '5433:5433'
    volumes:
      - 'vertica_data:/opt/vertica/data'
    networks:
      - vertica_network
    healthcheck:
      test: ["CMD", "vsql", "-U", "dbadmin", "-c", "SELECT 1"]
      interval: 10s   # Проверять состояние каждые 10 секунд
      retries: 7      # Количество попыток перед тем, как считать сервис незапущенным
      start_period: 45s

  vertica_benchmark:
    build: './vertica'
    container_name: 'vertica_benchmark'
    depends_on:
      vertica:
        condition: service_healthy

networks:
  vertica_network:

volumes:
  vertica_data: