services:
  vertica:
    image: 'jbfavre/vertica:latest'
    container_name: 'vertica'
    ports:
      - '5433:5433'
    volumes:
      - 'vertica_data:/opt/vertica/data'
    networks:
      - vertica_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/vertica/bin/vsql -U dbadmin -c 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 7
      start_period: 50s

  vertica_benchmark:
    build: './vertica'
    container_name: 'vertica_benchmark'
    volumes:
      - 'benchmark_vertica_data:/opt/vertica/'
    networks:
      - vertica_network
    restart: 'no'
    depends_on:
      vertica:
        condition: service_healthy
    command: [ "sh", "-c", "python benchmark_vertica.py --total 100000 --batch_size 1000"]

networks:
  vertica_network:

volumes:
  vertica_data:
  benchmark_vertica_data: