[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

backoff = "^2.2.1"
elasticsearch = "^8.16.0"
psycopg = "^3.2.3"
pydantic = "^2.10.0"
pydantic-settings = "^2.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
