[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

clickhouse-driver = "^0.2.9"
kafka-python = "^2.0.4"
pydantic-settings = "^2.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
