"""initial migration

Revision ID: 264d292cb7d1
Revises: 
Create Date: 2025-03-20 00:16:52.011246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '264d292cb7d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'PUSH', 'OTHER', name='template_type_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('id', name=op.f('uq_templates_id')),
    schema='admin_panel'
    )
    op.create_table('admin_notifications',
    sa.Column('notification_type', postgresql.ENUM('REGISTRATION', 'NEW_EPISODES', 'NEW_FILMS', 'NEWS', 'PROMOTION', 'MOVIE_RECOMMENDATION', 'LIKE_NOTIFICATION', name='notification_types_enum'), nullable=False),
    sa.Column('delivery_type', postgresql.ENUM('EMAIL', 'MESSAGE', 'TELEGRAM', 'WEBSOCKET', name='delivery_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='notification_task_status_enum'), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['admin_panel.templates.id'], name=op.f('fk_admin_notifications_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_notifications')),
    sa.UniqueConstraint('id', name=op.f('uq_admin_notifications_id')),
    schema='admin_panel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_notifications', schema='admin_panel')
    op.drop_table('templates', schema='admin_panel')
    # ### end Alembic commands ###
