name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint-command: [ 'ruff', 'mypy' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lint command '${{ matrix.lint-command }}'
        run: ./run_lint.sh ${{ matrix.lint-command }}
      - name: Upload lint results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-${{ matrix.lint-command }}
          path: |
            ./src/.lint/
            ./tests/.lint/
          include-hidden-files: true

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12', '3.13' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: PYTHON_VERSION=${{ matrix.python-version }} ./run_tests.sh
