name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint-command: [ 'ruff', 'mypy' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lint command '${{ matrix.lint-command }}'
        run: ./run_lint.sh ${{ matrix.lint-command }}
